# Generated by Django 6.1.1 on 2026-10-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent_app', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingenquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking Enquiry', 'verbose_name_plural': 'Booking Enquiries'},
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
