# Generated by Django 6.1.1 on 2026-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent_app', '0003_alter_bookingenquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
